/* ************************************************************************ *
 *    Even Fibonacci Numbers, 2018 VERSION                                  *
 *    each new  them in Fibonacci sequence is generated by adding the pre-  *
 *    vious terms. By starting with 1 and 2, the first 10 terms will be:    *
 *                  1,2,3,5,8,13,21,34,55,89...                             *
 *    By considering the terms in the Fibonnaci sequence whose values do    *
 *    not exceed four million, find the sum of even-valued terms.           *
 *    BRIEF_DESCRIPTION                                                     *
 *                                                                          *
 *    Copyright (C) 2018 by Gardenia Georgia Barbosa de Siqueira            *
 *                                                                          *
 *    This program is free software; you can redistribute it and/or modify  *
 *    it under the terms of the GNU General Public License as published by  *
 *    the Free Software Foundation; either version 2 of the License, or     *
 *    (at your option) any later version.                                   *
 *                                                                          *
 *    This program is distributed in the hope that it will be useful,       *
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *    GNU General Public License for more details.                          *
 *                                                                          *
 *    You should have received a copy of the GNU General Public License     *
 *    along with this program; if not, write to the                         *
 *    Free Software Foundation, Inc.,                                       *
 *    59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                          *
 *    To contact the author, please write to:                               *
 *    Gardenia Georgia Barbosa de Siqueira <gardenia.georgia.b.s@gmail.com> *
 *    Webpage: http://www.upe.com                                           *
 *    Phone: +55 (81) 99785-0393                                            *
 * ************************************************************************ *
 * 
 */

#include <stdio.h>
#include <stdlib.h>

#define MAX 4000000

int main(void)
{
    int N1 = 1;
    int N2 = 2;
    int N3 = 0;
    int soma = 2;
    
    while(1)
    {
        N3 = N1 + N2;
        if(N3 > MAX)
            break;
        if(!(N3 & 0X1))
            soma += N3;

        N1 = N2;
        N2 = N3;
    }
    printf("Soma de todos os pares menores que 4.000.000 eh %d\n",soma);

    return EXIT_SUCCESS;
}

